2017Blog/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2017Blog.Models;
using System.Web.Helpers;
using System.IO; 

namespace _2017Blog.Controllers
{
    public class UyeController : Controller
    {

        mvcblogDB db = new mvcblogDB();
       
        public ActionResult Index(int id)
        {
            var uye = db.Uyes.Where(u => u.UyeID == id).SingleOrDefault();
            if (Convert.ToInt32(Session["uyeid"])!=uye.UyeID) //uye id browse kısmına farklı id yazıp diğer üyelerin sayfasına erişemesin
            {
                return HttpNotFound();
            }
            return View(uye);
        }
       
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Uye uye)
        {
            var login = db.Uyes.Where(u => u.KullaniciAdi == uye.KullaniciAdi).Single();
            if (login != null)
            {
                if (login.KullaniciAdi == uye.KullaniciAdi && login.Email == uye.Email && login.Sifre == uye.Sifre)
                {
                    Session["uyeid"] = login.UyeID;
                    Session["kullaniciadi"] = login.KullaniciAdi;
                    Session["yetkiid"] = login.YetkiID;
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
        public ActionResult Logout()
        {

            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", "Home");

        }

        public ActionResult Create()
        {
            Session["uyeid"] = null;
            Session.Abandon();//session sonlandırma
            return View();  
        }
        [HttpPost] //butona tıklandığında 
        public ActionResult Create(Uye uye,HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto!=null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/UyeFoto/" + newfoto);
                    uye.Foto = "/Uploads/UyeFoto/" + newfoto;
                    uye.YetkiID = 1;
                    db.Uyes.Add(uye);
                    db.SaveChanges();
                    Session["uyeid"] = uye.UyeID;
                    Session["kullaniciadi"] = uye.KullaniciAdi;
                    return RedirectToAction("Index", "Home");// ındex e gonderdik
                }
                else
                {
                    ModelState.AddModelError("Fotograf", "Fotograf seçiniz.");
                }
            } 

            return View(uye);
        }
        public ActionResult Edit(int id) {

            var uye = db.Uyes.Where(u => u.UyeID == id).SingleOrDefault();
            if (Convert.ToInt32(Session["uyeid"])!=uye.UyeID)
            {
                return HttpNotFound();
            }
            
            return View(uye);

        }
        [HttpPost]
        public ActionResult Edit(Uye uye,int id,HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                var uyes = db.Uyes.Where(u => u.UyeID == id).SingleOrDefault();
                if (Foto!=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(uye.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(uyes.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/UyeFoto/" + newfoto);
                    uyes.Foto = "/Uploads/UyeFoto/" + newfoto;
                     }   
                    uyes.AdSoyad = uye.AdSoyad;
                    uyes.KullaniciAdi = uye.KullaniciAdi;
                    uyes.Sifre = uye.Sifre;
                    uyes.Email = uye.Email;
                    db.SaveChanges();
                    Session["kullaniciadi"] = uye.KullaniciAdi;
                    return RedirectToAction("Index", "Home",new { id = uyes.UyeID });
                
            }
            return View();

        }
    }
}

2017Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>2017 Blog</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/blog-home.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="~/Home/Index/">2017Blog</a>
            
            <div class="collapse navbar-brand" id="navbarResponsive" style="float:right; margin: 0">
                <ul class="navbar-nav ml-auto" style="display:inline-block">
                  
                    <li class="nav-item" style="float:left; margin-left : 25px">
                        <a class="nav-link" href="~/Home/Index/">Home</a>
                    </li>

                    <li class="nav-item" style="float:left; margin-left : 25px">
                        <a class="nav-link" href="~/Home/Hakkimizda/">Hakkımızda</a>
                    </li>
                    <li class="nav-item" style="float:left; margin-left : 25px">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item"  style="float:left; margin-left : 25px">
                        <a class="nav-link" href="~/Home/İletisim/">İletişim</a>
                    </li>
                    @if (Session["uyeid"] != null)
                    {
                        <li class="nav-item"  style="float:left; margin-left : 25px">
                            <a class="nav-link" href="/Uye/Index/@Session["uyeid"]">@Session["kullaniciadi"].ToString()</a>
                        </li>

                        <li class="nav-item"  style="float:left; margin-left : 25px">
                            <a class="nav-link nav-logout" href="#" onclick="location.href='@Url.Action("Logout", "Uye")'">Çıkış</a>
                           
                        </li>
                        if (Convert.ToInt32(Session["yetkiid"]) == 1)
                        {
                            <li class="nav-item"  style="float:left; margin-left : 25px">
                                <a class="nav-link" href="/Admin/Index/" target="_blank">Admin Paneli</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item"  style="float:left; margin-left : 25px">
                            <a class="nav-link" href="/Uye/Login/">Giriş</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">

                @RenderBody()
            </div>




            <!-- First Blog Post -->
            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Search</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
                <!-- Categories Widget -->
                <div class="card my-4">
                    <div class="col-lg-6">

                        @{
                            Html.RenderAction("KategoriPartial", "Home");
                        }

                    </div>
                </div>
            </div>
            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Side Widget</h5>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    @*</div>*@
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; @DateTime.Now.Year</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/css/jquery.js"></script>
    <script src="~/Content/css/popper.min.js"></script>
    <script src="~/Content/css/bootstrap.min.js"></script>
</body>
</html>