2017Blog/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2017Blog.Models;
using System.Web.Helpers;
using System.IO;

namespace _2017Blog.Controllers
{
    public class AdminMakaleController : Controller
    {
        mvcblogDB db = new mvcblogDB();

        // GET: AdminMakale
        public ActionResult Index()
        {
            var makales = db.Makalelers.ToList();
            return View(makales);
        }

        // GET: AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            
            return View();
        }

        // GET: AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategoris, "KategoriID", "KategoriAd");
            return View();
        }

        // POST: AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makaleler makale,string etiketler,HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
               
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = "/Uploads/MakaleFoto/" + newfoto;

                    
                

                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }
                db.Makalelers.Add(makale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
                return View(makale);
            
        }

        // GET: AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makalelers.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategoris,"KategoriID","KategoriAd",makale.KategoriID);
            return View(makale);
        }

        // POST: AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id,HttpPostedFileBase Foto,Makaleler makale) 
        {
            try
            {
                var makales = db.Makalelers.Where(m => m.MakaleID == id).SingleOrDefault();
                if (Foto!=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.KategoriID = makale.KategoriID;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                ViewBag.KategoriID = new SelectList(db.Kategoris, "KategoriID", "KategoriAd", makale.KategoriID);
                return View(makale);
            }
        }

        // GET: AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = db.Makalelers.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makalelers.Where(m => m.MakaleID == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }

                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }
                foreach (var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }
                foreach (var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i); 
                }
                db.Makalelers.Remove(makales);
                db.SaveChanges();
                    
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

2017Blog/Views/AdminMakale/Create.cshtml
@model _2017Blog.Models.Makaleler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Makale Oluştur</h2>

@using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makaleler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           @Html.Label("Etiketler",new {@class="control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBox("Etiketler") 
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

2017Blog/Views/AdminMakale/Delete.cshtml
@model _2017Blog.Models.Makaleler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Silmek istiyor musunuz?</h3>
<div>
    <h4>Makaleler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            <img src="@Model.Foto" width="110" alt="Alternate Text" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Okunma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

2017Blog/Views/AdminMakale/Edit.cshtml
@model _2017Blog.Models.Makaleler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Düzenle</h2>

@using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MakaleID)

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="75" src="@Model.Foto" alt="Alternate Text" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

2017Blog/Views/AdminMakale/Index.cshtml
@model IEnumerable<_2017Blog.Models.Makaleler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Makaleler</h2>

<p>
    @Html.ActionLink("Yeni Makale", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Icerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tarih)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UyeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Okunma)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Baslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Icerik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UyeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Okunma)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.MakaleID }) |
            @Html.ActionLink("Detay", "Details", new { id=item.MakaleID }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.MakaleID })
        </td>
    </tr>
}
     
</table>